tool:
  nodejs:
    installations:
    - name: "node"
      properties:
      - installSource:
          installers:
          - nodeJSInstaller:
              id: "14.16.1"
              npmPackagesRefreshHours: 72
unclassified:
  scmGit:
    globalConfigName: Eclipse Ditto committers
    globalConfigEmail: ditto-dev@eclipse.org
