tool:
  nodejs:
    installations:
    - name: "node"
      properties:
      - installSource:
          installers:
          - nodeJSInstaller:
              id: "14.17.3"
              npmPackagesRefreshHours: 72
unclassified:
  scmGit:
    globalConfigName: Eclipse Kapua committers
    globalConfigEmail: kapua-dev@eclipse.org
