#*******************************************************************************
# Copyright (c) 2019 Eclipse Foundation and others.
# This program and the accompanying materials are made available
# under the terms of the Eclipse Public License 2.0
# which is available at http://www.eclipse.org/legal/epl-v20.html,
# or the MIT License which is available at https://opensource.org/licenses/MIT.
# SPDX-License-Identifier: EPL-2.0 OR MIT
#*******************************************************************************
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    org.eclipse.cbi.jiro/project.shortname: "geowave"
    org.eclipse.cbi.jiro/project.fullName: "locationtech.geowave"
    org.eclipse.cbi.jiro/kind: "master"
  annotations:
    org.eclipse.cbi.jiro/jenkins.version: "latest"
    org.eclipse.cbi.jiro/jenkins.actualVersion: "2.222.4"
    org.eclipse.cbi.jiro/kubernetes.master.namespace: "geowave"
  namespace: "geowave"
  name: jenkins-config
data:
  jenkins.yaml: |
    # GENERATED FILE - DO NOT EDIT
    #*******************************************************************************
    # Copyright (c) 2018 Eclipse Foundation and others.
    # This program and the accompanying materials are made available
    # under the terms of the Eclipse Public License 2.0
    # which is available at http://www.eclipse.org/legal/epl-v20.html,
    # or the MIT License which is available at https://opensource.org/licenses/MIT.
    # SPDX-License-Identifier: EPL-2.0 OR MIT
    #*******************************************************************************
    jenkins:
      numExecutors: 0
      scmCheckoutRetryCount: 2
      mode: EXCLUSIVE
      systemMessage: ""
    
      disableRememberMe: false
      agentProtocols:
        - "JNLP4-connect"
        - "Ping"
    
      authorizationStrategy:
        projectMatrix:
          permissions:
            - "Overall/Administer:admins"
            - "Job/Read:anonymous"
            - "Overall/Read:anonymous"
            - "Job/ExtendedRead:common"
            - "Agent/Build:locationtech.geowave"
            - "Credentials/View:locationtech.geowave"
            - "Gerrit/ManualTrigger:locationtech.geowave"
            - "Gerrit/Retrigger:locationtech.geowave"
            - "Job/Build:locationtech.geowave"
            - "Job/Cancel:locationtech.geowave"
            - "Job/Configure:locationtech.geowave"
            - "Job/Create:locationtech.geowave"
            - "Job/Delete:locationtech.geowave"
            - "Job/Move:locationtech.geowave"
            - "Job/Read:locationtech.geowave"
            - "Job/Workspace:locationtech.geowave"
            - "Overall/Read:locationtech.geowave"
            - "Run/Delete:locationtech.geowave"
            - "Run/Replay:locationtech.geowave"
            - "Run/Update:locationtech.geowave"
            - "SCM/Tag:locationtech.geowave"
            - "View/Configure:locationtech.geowave"
            - "View/Create:locationtech.geowave"
            - "View/Delete:locationtech.geowave"
            - "View/Read:locationtech.geowave"
    
      markupFormatter: rawHtml
      crumbIssuer:
        standard:
           excludeClientIPFromCrumb: false
      remotingSecurity:
        enabled: true
    
      securityRealm:
        ldap:
          configurations:
            - displayNameAttributeName: cn
              groupSearchBase: ou=group
              rootDN: dc=eclipse,dc=org
              server: ldaps://ldapcluster.eclipse.org
              userSearch: mail={0}
              mailAddressAttributeName: mail
    
      clouds:
      - kubernetes:
          name: "kubernetes"
          containerCapStr: "2"
          jenkinsUrl: "http://jenkins-ui.geowave.svc.cluster.local/geowave"
          jenkinsTunnel: "jenkins-discovery.geowave.svc.cluster.local:50000"
          maxRequestsPerHostStr: "32"
          namespace: "geowave"
          podRetention: "never"
          templates:
          - containers:
            - image: docker.io/eclipsecbi/jiro-agent-basic:remoting-4.2.1
              alwaysPullImage: true
              livenessProbe:
                failureThreshold: 0
                initialDelaySeconds: 0
                periodSeconds: 0
                successThreshold: 0
                timeoutSeconds: 0
              name: "jnlp"
              resourceLimitCpu: "2000m"
              resourceRequestCpu: "1000m"
              resourceLimitMemory: "4096Mi"
              resourceRequestMemory: "4096Mi"
              ttyEnabled: true
              command: ""
              args: ""
            instanceCap: -1
            name: "basic"
            namespace: "geowave"
            nodeUsageMode: NORMAL
            label: ""
            envVars:
            - envVar:
                key: "IBM_JAVA_OPTIONS"
                value: "-XX:+IgnoreUnrecognizedVMOptions -XX:+IdleTuningCompactOnIdle -XX:+IdleTuningGcOnIdle"
            - envVar:
                key: "JAVA_OPTS"
                value: ""
            - envVar:
                key: "JAVA_TOOL_OPTIONS"
                value: ""
            - envVar:
                key: "JNLP_PROTOCOL_OPTS"
                value: "-showversion -XshowSettings:vm -Xmx256m -Dsun.zip.disableMemoryMapping=true -Dorg.jenkinsci.remoting.engine.JnlpProtocol3.disabled=true -Dorg.jenkinsci.plugins.gitclient.CliGitAPIImpl.useSETSID=true"
            - envVar:
                key: "OPENJ9_JAVA_OPTIONS"
                value: "-XX:+IgnoreUnrecognizedVMOptions -XX:+IdleTuningCompactOnIdle -XX:+IdleTuningGcOnIdle"
            - envVar:
                key: "_JAVA_OPTIONS"
                value: ""
            volumes:
            - persistentVolumeClaim:
                claimName: "tools-claim-jiro-geowave"
                mountPath: "/opt/tools"
                readOnly: true
            - configMapVolume:
                configMapName: "known-hosts"
                mountPath: "/home/jenkins/.ssh/"
            - emptyDirVolume:
                memory: false
                mountPath: "/home/jenkins/"
            - emptyDirVolume:
                memory: false
                mountPath: "/home/jenkins/.m2/repository"
            - emptyDirVolume:
                memory: false
                mountPath: "/home/jenkins/.m2/wrapper"
            workspaceVolume:
              emptyDirWorkspaceVolume:
                memory: false
            yaml: |
              apiVersion: v1
              kind: Pod
              spec:
                containers:
                - name: jnlp
                  volumeMounts:
                  - name: m2-secret-dir
                    mountPath: /home/jenkins/.m2/settings-security.xml
                    subPath: settings-security.xml
                    readOnly: true
                  - name: m2-secret-dir
                    mountPath: /home/jenkins/.m2/settings.xml
                    subPath: settings.xml
                    readOnly: true
                  - name: m2-dir
                    mountPath: /home/jenkins/.m2/toolchains.xml
                    subPath: toolchains.xml
                    readOnly: true
                  - name: m2-dir
                    mountPath: /home/jenkins/.mavenrc
                    subPath: .mavenrc
                    readOnly: true
                volumes:
                - name: m2-secret-dir
                  secret:
                    secretName: m2-secret-dir
                - name: m2-dir
                  configMap:
                    name: m2-dir
          - containers:
            - image: docker.io/eclipsecbi/jiro-agent-centos-7:remoting-4.2.1
              alwaysPullImage: true
              livenessProbe:
                failureThreshold: 0
                initialDelaySeconds: 0
                periodSeconds: 0
                successThreshold: 0
                timeoutSeconds: 0
              name: "jnlp"
              resourceLimitCpu: "2000m"
              resourceRequestCpu: "1000m"
              resourceLimitMemory: "4096Mi"
              resourceRequestMemory: "4096Mi"
              ttyEnabled: true
              command: ""
              args: ""
            instanceCap: -1
            name: "centos-7"
            namespace: "geowave"
            nodeUsageMode: EXCLUSIVE
            label: "migration jipp-migration centos centos-7"
            envVars:
            - envVar:
                key: "IBM_JAVA_OPTIONS"
                value: "-XX:+IgnoreUnrecognizedVMOptions -XX:+IdleTuningCompactOnIdle -XX:+IdleTuningGcOnIdle"
            - envVar:
                key: "JAVA_OPTS"
                value: ""
            - envVar:
                key: "JAVA_TOOL_OPTIONS"
                value: ""
            - envVar:
                key: "JNLP_PROTOCOL_OPTS"
                value: "-showversion -XshowSettings:vm -Xmx256m -Dsun.zip.disableMemoryMapping=true -Dorg.jenkinsci.remoting.engine.JnlpProtocol3.disabled=true -Dorg.jenkinsci.plugins.gitclient.CliGitAPIImpl.useSETSID=true"
            - envVar:
                key: "OPENJ9_JAVA_OPTIONS"
                value: "-XX:+IgnoreUnrecognizedVMOptions -XX:+IdleTuningCompactOnIdle -XX:+IdleTuningGcOnIdle"
            - envVar:
                key: "_JAVA_OPTIONS"
                value: ""
            volumes:
            - persistentVolumeClaim:
                claimName: "tools-claim-jiro-geowave"
                mountPath: "/opt/tools"
                readOnly: true
            - configMapVolume:
                configMapName: "known-hosts"
                mountPath: "/home/jenkins/.ssh/"
            - emptyDirVolume:
                memory: false
                mountPath: "/home/jenkins/"
            - emptyDirVolume:
                memory: false
                mountPath: "/home/jenkins/.m2/repository"
            - emptyDirVolume:
                memory: false
                mountPath: "/home/jenkins/.m2/wrapper"
            workspaceVolume:
              emptyDirWorkspaceVolume:
                memory: false
            yaml: |
              apiVersion: v1
              kind: Pod
              spec:
                containers:
                - name: jnlp
                  volumeMounts:
                  - name: m2-secret-dir
                    mountPath: /home/jenkins/.m2/settings-security.xml
                    subPath: settings-security.xml
                    readOnly: true
                  - name: m2-secret-dir
                    mountPath: /home/jenkins/.m2/settings.xml
                    subPath: settings.xml
                    readOnly: true
                  - name: m2-dir
                    mountPath: /home/jenkins/.m2/toolchains.xml
                    subPath: toolchains.xml
                    readOnly: true
                  - name: m2-dir
                    mountPath: /home/jenkins/.mavenrc
                    subPath: .mavenrc
                    readOnly: true
                volumes:
                - name: m2-secret-dir
                  secret:
                    secretName: m2-secret-dir
                - name: m2-dir
                  configMap:
                    name: m2-dir
    security:
      apiToken:
        creationOfLegacyTokenEnabled: false
        tokenGenerationOnCreationEnabled: false
        usageStatisticsEnabled: true
      queueItemAuthenticator:
        authenticators:
        - global:
            strategy: "triggeringUsersAuthorizationStrategy"
      sSHD:
        port: -1
    
    unclassified:
      location:
        adminAddress: ci-admin@eclipse.org
        url: https://ci.eclipse.org/geowave
    
      mailer:
        replyToAddress: ci-admin@eclipse.org
        smtpHost: mail.eclipse.org
    
      extendedEmailPublisher:
        defaultContentType: "text/html"
    
      globalDefaultFlowDurabilityLevel:
        durabilityHint: PERFORMANCE_OPTIMIZED
    
      simple-theme-plugin:
        elements:
        - cssUrl:
            url: "/geowave/userContent/theme/quicksilver.css"
        - cssUrl:
            url: "//fonts.googleapis.com/css?family=Libre+Franklin:400,700,300,600,100"
        - jsUrl:
            url: "/geowave/userContent/theme/title.js"
    
      buildDiscarders:
        configuredBuildDiscarders:
        - "jobBuildDiscarder"
        - simpleBuildDiscarder:
            discarder:
              logRotator:
                artifactNumToKeepStr: "5"
                numToKeepStr: "128"
    
    tool:
      jdk:
        installations:
        - name: "openjdk-latest"
          home: "/opt/tools/java/openjdk/latest"
        - name: "openjdk-jdk15-latest"
          home: "/opt/tools/java/openjdk/jdk-15/latest"
        - name: "openjdk-jdk14-latest"
          home: "/opt/tools/java/openjdk/jdk-14/latest"
        - name: "openjdk-jdk13-latest"
          home: "/opt/tools/java/openjdk/jdk-13/latest"
        - name: "openjdk-jdk12-latest"
          home: "/opt/tools/java/openjdk/jdk-12/latest"
        - name: "openjdk-jdk11-latest"
          home: "/opt/tools/java/openjdk/jdk-11/latest"
        - name: "openjdk-jdk10-latest"
          home: "/opt/tools/java/openjdk/jdk-10/latest"
        - name: "openjdk-jdk9-latest"
          home: "/opt/tools/java/openjdk/jdk-9/latest"
        - name: "adoptopenjdk-hotspot-latest"
          home: "/opt/tools/java/adoptopenjdk/hotspot-latest"
        - name: "adoptopenjdk-hotspot-jdk12-latest"
          home: "/opt/tools/java/adoptopenjdk/hotspot-jdk-12/latest"
        - name: "adoptopenjdk-hotspot-jdk11-latest"
          home: "/opt/tools/java/adoptopenjdk/hotspot-jdk-11/latest"
        - name: "adoptopenjdk-hotspot-jdk10-latest"
          home: "/opt/tools/java/adoptopenjdk/hotspot-jdk-10/latest"
        - name: "adoptopenjdk-hotspot-jdk9-latest"
          home: "/opt/tools/java/adoptopenjdk/hotspot-jdk-9/latest"
        - name: "adoptopenjdk-hotspot-jdk8-latest"
          home: "/opt/tools/java/adoptopenjdk/hotspot-jdk-8/latest"
        - name: "adoptopenjdk-openj9-latest"
          home: "/opt/tools/java/adoptopenjdk/openj9-latest"
        - name: "adoptopenjdk-openj9-jdk12-latest"
          home: "/opt/tools/java/adoptopenjdk/openj9-jdk-12/latest"
        - name: "adoptopenjdk-openj9-jdk11-latest"
          home: "/opt/tools/java/adoptopenjdk/openj9-jdk-11/latest"
        - name: "adoptopenjdk-openj9-jdk10-latest"
          home: "/opt/tools/java/adoptopenjdk/openj9-jdk-10/latest"
        - name: "adoptopenjdk-openj9-jdk9-latest"
          home: "/opt/tools/java/adoptopenjdk/openj9-jdk-9/latest"
        - name: "adoptopenjdk-openj9-jdk8-latest"
          home: "/opt/tools/java/adoptopenjdk/openj9-jdk-8/latest"
        - name: "oracle-latest"
          home: "/opt/tools/java/oracle/latest"
        - name: "oracle-jdk10-latest"
          home: "/opt/tools/java/oracle/jdk-10/latest"
        - name: "oracle-jdk9-latest"
          home: "/opt/tools/java/oracle/jdk-9/latest"
        - name: "oracle-jdk8-latest"
          home: "/opt/tools/java/oracle/jdk-8/latest"
        - name: "oracle-jdk7-latest"
          home: "/opt/tools/java/oracle/jdk-7/latest"
        - name: "oracle-jdk6-latest"
          home: "/opt/tools/java/oracle/jdk-6/latest"
        - name: "oracle-jdk5-latest"
          home: "/opt/tools/java/oracle/jdk-5/latest"
        - name: "ibm-jdk8-latest"
          home: "/opt/tools/java/ibm/jdk-8/latest"
        - name: "ibm-latest"
          home: "/opt/tools/java/ibm/latest"
      ant:
        installations:
        - name: "apache-ant-latest"
          home: ""
          properties:
          - installSource:
              installers:
              - antFromApache:
                  id: "1.10.5"
      maven:
        installations:
        - name: "apache-maven-latest"
          home: "/opt/tools/apache-maven/latest"
        - name: "apache-maven-3.6.3"
          home: "/opt/tools/apache-maven/3.6.3"
        - name: "apache-maven-3.6.0"
          home: "/opt/tools/apache-maven/3.6.0"
        - name: "apache-maven-3.5.4"
          home: "/opt/tools/apache-maven/3.5.4"
        - name: "apache-maven-3.3.9"
          home: "/opt/tools/apache-maven/3.3.9"
        - name: "apache-maven-3.2.5"
          home: "/opt/tools/apache-maven/3.2.5"
      git:
        installations:
        - name: "Default"
          home: "git"
