jenkins:
  nodes:
  - permanent:
      labelString: "external"
      launcher:
        ssh:
          credentialsId: "f83258dd-f206-441c-991d-d9f754c4f6fa"
          host: "116.203.100.226"
          port: 22
          sshHostKeyVerificationStrategy:
            manuallyProvidedKeyVerificationStrategy:
              key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAoSSFhyrxA22Bsphc4ktfjwwHzJ+w3sX9ixNFIVks7swLdYnkoe6pUoeo4KNqvcEYLwcur/NSS83nKO3uk/aCXb222zeegxMWbJluuP5+Ora8RY5Vd5JhLridorPHx+xuSNhnowx5VCkBA7MAzapHx/6KIHVKspVKFW0Ddd2difyDBt3w8hghiNub6LV8Oj0nWmTLyWgcP0TgK2X2P4EcgBLLn9TJXqIqutzwlFjr0vRs3NxkbUm4vmILv/v3/LmsfeY+TQsXbjKOAKPmQ/b/DSfUzjqf7TIxQDuTYlSxWEYTEceKDJiPCPntyiRtuqyvacbiHtr6/g/w/DOiYRJb"
      mode: EXCLUSIVE
      name: "external-agent-01"
      numExecutors: 1
      remoteFS: "/home/xtextbot"
  - permanent:
      labelString: "external"
      launcher:
        ssh:
          credentialsId: "f83258dd-f206-441c-991d-d9f754c4f6fa"
          host: "116.203.94.5"
          port: 22
          sshHostKeyVerificationStrategy:
            manuallyProvidedKeyVerificationStrategy:
              key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDTgsftTryYb2zdbL3cgYyV6XEqfLX4UIHSe44lNf5nLDiVCb/w32eEz8aR5krb4M5M5IsDtPFRW/I4mpeiLBkvP/baNdqyZJxKrOCRPOmH7PGu6hhfPOVjjgN3mtoF4Cl01i/7kwqA+2palztf1LMfipTkps8gIWnR1qbZeOtdyE+5nCW2tn0lKHW7FCwRZZAzomAtFx5izgATY6LgFOhNJbWrQ3MdK3n26PR9DjLWqm7isEQg1F/+cbFmmWAsITwL+mB0wtXV2fPwXeEsQbuaL6f04mYzUuekbB/3ppraL9nqCSKrYsq6RQp2Pa5fZ5jR6EWLTNHpEEIXLGcbtvpN"
      mode: EXCLUSIVE
      name: "external-agent-02"
      numExecutors: 1
      remoteFS: "/home/xtextbot"